#!/bin/bash

selfip="$(ip -o -4 route show | grep -o -E "src\s+([0-9]{1,3}[.]){3}[0-9]{1,3}" | head -1 | cut -d' ' -f2)"
ipset="false"
port="4656"
action="set client"

prog="auto"
#sampleRate=48000
sampleRate=44100
#quantum=1024
quantum=512
frmt="S16"
#frmt="F32"

## Read command line:
while [ $# -gt 0 ]; do

	key="$1"

	case "$1" in

		connect|c)
			action="set client"
			shift
			;;

		listen|l|server)
			action="set server"
			shift
			;;

		list|ls)
			action="list"
			shift
			;;
		
		del|delete)
			action="delete"
			shift
			;;

		--port=*)
			port="${key:7}"
			shift
			;;

		--port)
			shift
			port="$1"
			shift
			;;

		--ip-auto)
			ip="$selfip"
			shift
			;;

		--ip=*)
			ip="${key:5}"
			shift
			;;

		--ip)
			shift
			ip="$1"
			shift
			;;
	esac

done

if [ "$prog" == "auto" ]; then
	command -v pw-metadata > /dev/null && prog="pipewire"
fi

if [ "$prog" == "pipewire" ]; then
	pw-metadata -n settings 0 clock.force-rate "$sampleRate"
	pw-metadata -n settings 0 clock.force-quantum "$quantum"
	pw-metadata -n settings 0 clock.format $frmt
fi

if [ "$action" == "set client" ]; then

	pactl unload-module module-tunnel-sink
	## export PULSE_SERVER=tcp:$ip:$port
	pactl load-module module-tunnel-sink server=tcp:$ip:$port
	sinkname="$(pactl list short sources | grep "$ip" | cut -d$'\t' -f1)"
	pactl load-module module-tunnel-sink server=tcp:$ip:$port tsched=1 rate=48000 format=s16le channels=2 latency_msec=10
	pactl set-port-latency-offset $sinkname -200000
	pactl set-default-sink $sinkname

	# pactl unload-module module-rtp-send
	# pactl load-module module-rtp-send source=them.monitor destication_ip=$ip
elif [ "$action" == "set server" ]; then

	pactl unload-module module-native-protocol-tcp

	pactl load-module module-native-protocol-tcp port="$port" listen="$ip" ;latency_msec=50 auth-anonymous=true record=0 playback=1

	# pactl unload-module module-rtp-recv
	# pactl load-module module-rtp-recv sink-reciveon latency_msec=50 sap_address=0.0.0.0

elif [ "$action" == "delete" ]; then

	sid="$(pactl list short | grep 'server=' | cut -d$'\t' -f1 | head -n1)"
	[ "$sid" != "" ] && pactl unload-module "$sid"
	sid="$(pactl list short | grep 'listen=' | cut -d$'\t' -f1 | head -n1)"
	[ "$sid" != "" ] && pactl unload-module "$sid"

elif [ "$action" == "list" ]; then

	pactl list short sources

fi
